"""Convert the Yale Bright Star Catalogue (5th revised ed.) to a compact CSV.

Source: Hoffleit & Warren (1991), CDS catalogue V/50
        https://cdsarc.cds.unistra.fr/ftp/V/50/  (files: ReadMe, catalog.gz)

Usage:
    python convert_bsc5.py <catalog.gz> <output.csv>

Columns (byte positions from the V/50 ReadMe):
    HR 1-4, Name 5-14, RA J2000 76-83, Dec J2000 84-90, Vmag 103-107, B-V 110-114.
Entries without a J2000 position (a few non-stellar objects) are skipped.
A missing B-V is written as an empty field.
"""

import gzip
import sys


def field(line, first, last):
    """1-based inclusive byte range, stripped."""
    return line[first - 1:last].strip()


def convert(src, dst):
    rows = []
    with gzip.open(src, 'rt', encoding='ascii', errors='replace') as f:
        for line in f:
            line = line.rstrip('\n').ljust(197)
            if not field(line, 76, 77) or not field(line, 103, 107):
                continue
            hr = int(field(line, 1, 4))
            name = ' '.join(field(line, 5, 14).split())
            ra = (int(field(line, 76, 77)) + int(field(line, 78, 79)) / 60.0
                  + float(field(line, 80, 83)) / 3600.0) * 15.0
            dec = (int(field(line, 85, 86)) + int(field(line, 87, 88)) / 60.0
                   + int(field(line, 89, 90)) / 3600.0)
            if field(line, 84, 84) == '-':
                dec = -dec
            vmag = float(field(line, 103, 107))
            bv = field(line, 110, 114)
            rows.append((hr, ra, dec, vmag, bv, name))

    with open(dst, 'w', encoding='ascii', newline='\n') as out:
        out.write('# Yale Bright Star Catalogue, 5th revised ed. (Hoffleit & Warren 1991), CDS V/50.\n')
        out.write('# Generated by tools/stars/convert_bsc5.py. J2000 positions, epoch 2000.0.\n')
        out.write('hr,ra_deg,dec_deg,vmag,bv,name\n')
        for hr, ra, dec, vmag, bv, name in rows:
            out.write(f'{hr},{ra:.5f},{dec:.5f},{vmag:.2f},{bv},{name}\n')
    print(f'{len(rows)} stars written to {dst}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    convert(sys.argv[1], sys.argv[2])
