"""Convert the HYG star database to the compact CSV the program reads.

Source: HYG database v4.4 (astronexus), CC BY-SA 4.0
        https://codeberg.org/astronexus/hyg  (file data/hyg/CURRENT/hyg_v44.csv.gz)
        A merge of Hipparcos, the Yale Bright Star Catalogue and the Gliese
        Catalogue of Nearby Stars, with distances from the Hipparcos parallaxes.

Usage:
    python convert_hyg.py <hyg_v44.csv.gz> <output.csv>

The output keeps every star that could be brighter than V = FAINT_MAG for a
viewer anywhere within MAX_VIEWER_PC of the Sun (the scenes around alpha Cen
and TRAPPIST-1 see the sky from there): from such a viewer a star at distance d
is at least d - MAX_VIEWER_PC away. Stars without a usable parallax (HYG
dist >= 100000) are kept by their magnitude from Earth and taken as infinitely
far. The Sun itself is left out (it is a body in the scenes that need it).

Columns: hip,hr,ra_deg,dec_deg,dist_pc,vmag,bv,name
    dist_pc empty: unknown (infinitely far); bv empty: unknown;
    name: the proper name, else the Bayer/Flamsteed designation, else the Gliese number.
"""

import csv
import gzip
import math
import sys

FAINT_MAG = 6.5
MAX_VIEWER_PC = 15.0
NO_DISTANCE_PC = 100000.0


def number(text):
    try:
        return float(text)
    except ValueError:
        return None


def keep(vmag, dist):
    if dist is None:
        return vmag <= FAINT_MAG
    nearest = max(dist - MAX_VIEWER_PC, 0.01)
    return vmag + 5.0 * math.log10(nearest / dist) <= FAINT_MAG


def convert(src, dst):
    rows = []
    with gzip.open(src, 'rt', encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if r['proper'] == 'Sol':
                continue
            vmag = number(r['mag'])
            if vmag is None:
                continue
            dist = number(r['dist'])
            if dist is not None and (dist <= 0.0 or dist >= NO_DISTANCE_PC):
                dist = None
            if not keep(vmag, dist):
                continue
            name = r['proper'] or ' '.join(r['bf'].split()) or r['gl']
            rows.append((r['hip'], r['hr'], float(r['ra']) * 15.0, float(r['dec']),
                         '' if dist is None else f'{dist:.5g}', vmag, r['ci'], name.replace(',', ' ')))

    with open(dst, 'w', encoding='utf-8', newline='\n') as out:
        out.write('# HYG database v4.4 (astronexus, https://codeberg.org/astronexus/hyg), CC BY-SA 4.0.\n')
        out.write('# Generated by tools/stars/convert_hyg.py. J2000 positions, epoch 2000.0; distances in pc.\n')
        out.write(f'# Complete to V = {FAINT_MAG} for viewers within max_viewer_pc of the Sun.\n')
        out.write(f'# max_viewer_pc = {MAX_VIEWER_PC:g}\n')
        out.write('hip,hr,ra_deg,dec_deg,dist_pc,vmag,bv,name\n')
        for hip, hr, ra, dec, dist, vmag, bv, name in rows:
            out.write(f'{hip},{hr},{ra:.5f},{dec:.5f},{dist},{vmag:.2f},{bv},{name}\n')
    print(f'{len(rows)} stars written to {dst}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    convert(sys.argv[1], sys.argv[2])
